// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Settings/VoidRoguesInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace VoidRogues.Network
{
    public partial class @VoidRoguesInputActions : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }

        public @VoidRoguesInputActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""VoidRoguesInputActions"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""a1b2c3d4-e5f6-a7b8-c9d0-e1f2a3b4c5d6"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""11111111-1111-1111-1111-111111111111"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Aim"",
                    ""type"": ""Value"",
                    ""id"": ""22222222-2222-2222-2222-222222222222"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Fire"",
                    ""type"": ""Button"",
                    ""id"": ""33333333-3333-3333-3333-333333333333"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""44444444-4444-4444-4444-444444444444"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaab"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaac"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaad"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaae"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbba"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cccccccc-cccc-cccc-cccc-ccccccccccca"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cccccccc-cccc-cccc-cccc-cccccccccccb"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dddddddd-dddd-dddd-dddd-ddddddddddda"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dddddddd-dddd-dddd-dddd-dddddddddddb"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeeea"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeebb"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard&Mouse"",
            ""bindingGroup"": ""Keyboard&Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
            // Gameplay map
            m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
            m_Gameplay_Move     = m_Gameplay.FindAction("Move",     throwIfNotFound: true);
            m_Gameplay_Aim      = m_Gameplay.FindAction("Aim",      throwIfNotFound: true);
            m_Gameplay_Fire     = m_Gameplay.FindAction("Fire",     throwIfNotFound: true);
            m_Gameplay_Interact = m_Gameplay.FindAction("Interact", throwIfNotFound: true);
        }

        ~@VoidRoguesInputActions()
        {
            UnityEngine.Debug.Assert(!asset.IsActuallyEnabled(),
                "'" + asset.name + "' Input Actions are still enabled. Make sure to call Disable() before destroying an InputActionAsset.");
            Dispose();
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action) => asset.Contains(action);

        public IEnumerator<InputAction> GetEnumerator() => asset.GetEnumerator();

        IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();

        public void Enable()  => asset.Enable();
        public void Disable() => asset.Disable();

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
            => asset.FindAction(actionNameOrId, throwIfNotFound);

        public int FindBinding(InputBinding bindingMask, out InputAction action)
            => asset.FindBinding(bindingMask, out action);

        // ── Gameplay map ──────────────────────────────────────────────────────

        private InputActionMap m_Gameplay;
        private InputAction m_Gameplay_Move;
        private InputAction m_Gameplay_Aim;
        private InputAction m_Gameplay_Fire;
        private InputAction m_Gameplay_Interact;

        public struct GameplayActions
        {
            private @VoidRoguesInputActions m_Wrapper;

            public GameplayActions(@VoidRoguesInputActions wrapper) { m_Wrapper = wrapper; }

            public InputAction @Move     => m_Wrapper.m_Gameplay_Move;
            public InputAction @Aim      => m_Wrapper.m_Gameplay_Aim;
            public InputAction @Fire     => m_Wrapper.m_Gameplay_Fire;
            public InputAction @Interact => m_Wrapper.m_Gameplay_Interact;

            public InputActionMap Get() => m_Wrapper.m_Gameplay;

            public void Enable()  => Get().Enable();
            public void Disable() => Get().Disable();
            public bool enabled   => Get().enabled;

            public static implicit operator InputActionMap(GameplayActions set) => set.Get();

            public void AddCallbacks(IGameplayActions instance)
            {
                if (instance == null) return;
                @Move.started     += instance.OnMove;
                @Move.performed   += instance.OnMove;
                @Move.canceled    += instance.OnMove;
                @Aim.started      += instance.OnAim;
                @Aim.performed    += instance.OnAim;
                @Aim.canceled     += instance.OnAim;
                @Fire.started     += instance.OnFire;
                @Fire.performed   += instance.OnFire;
                @Fire.canceled    += instance.OnFire;
                @Interact.started     += instance.OnInteract;
                @Interact.performed   += instance.OnInteract;
                @Interact.canceled    += instance.OnInteract;
            }

            public void RemoveCallbacks(IGameplayActions instance)
            {
                if (instance == null) return;
                @Move.started     -= instance.OnMove;
                @Move.performed   -= instance.OnMove;
                @Move.canceled    -= instance.OnMove;
                @Aim.started      -= instance.OnAim;
                @Aim.performed    -= instance.OnAim;
                @Aim.canceled     -= instance.OnAim;
                @Fire.started     -= instance.OnFire;
                @Fire.performed   -= instance.OnFire;
                @Fire.canceled    -= instance.OnFire;
                @Interact.started     -= instance.OnInteract;
                @Interact.performed   -= instance.OnInteract;
                @Interact.canceled    -= instance.OnInteract;
            }

            public void SetCallbacks(IGameplayActions instance)
            {
                if (m_Wrapper.m_GameplayActionsCallbackInterface != null)
                    RemoveCallbacks(m_Wrapper.m_GameplayActionsCallbackInterface);
                m_Wrapper.m_GameplayActionsCallbackInterface = instance;
                AddCallbacks(instance);
            }
        }

        public GameplayActions @Gameplay => new GameplayActions(this);
        private IGameplayActions m_GameplayActionsCallbackInterface;

        // ── Control schemes ───────────────────────────────────────────────────

        private int m_KeyboardMouseSchemeIndex = -1;

        public InputControlScheme KeyboardMouseScheme
        {
            get
            {
                if (m_KeyboardMouseSchemeIndex == -1)
                    m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard&Mouse");
                return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
            }
        }

        private int m_GamepadSchemeIndex = -1;

        public InputControlScheme GamepadScheme
        {
            get
            {
                if (m_GamepadSchemeIndex == -1)
                    m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
                return asset.controlSchemes[m_GamepadSchemeIndex];
            }
        }

        // ── Callback interfaces ───────────────────────────────────────────────

        public interface IGameplayActions
        {
            void OnMove(InputAction.CallbackContext context);
            void OnAim(InputAction.CallbackContext context);
            void OnFire(InputAction.CallbackContext context);
            void OnInteract(InputAction.CallbackContext context);
        }
    }
}
